### ISSUE TITLE
Keyboard scaling issues on XA2

### ISSUE THREAD

**Issue by sigurg** [R-033/toeterm#14]
I installed toeterm on my XA2 (SfOS 3.0.0.8) and noticed that all the special keys (backspace, enter, shift, arrows, etc.) on the keyboard are scaled way too large. Also popup when switching keyboard layouts appears unintentionally large.

Here's a screenshot of the issue:
![toeterm-keyboard-xa2](https://user-images.githubusercontent.com/9652109/50368699-fd504500-058b-11e9-90df-86888118a738.png)

**Comment by direc85** [comment]
Hello! I [fixed the icon sizes](https://github.com/direc85/toeterm/commit/b029ab328d6e9a6856158c42e67675d6a5e0eb7b) in my fork, so I think this can be closed :)

**Comment by direc85** [comment]
I fixed the stupidly large font size, box positioning and text size vs. rectangle size issues, so now I consider the whole issue fixed ;)
