### ISSUE TITLE
Ctrl key misbehave

### ISSUE THREAD

**Issue by Self-Perfection** [R-033/toeterm#7]
ToeTerm v 1.3

Ctrl key misbehaves making impossible to use search in command history.

There are 3 visual states of Ctrl key:
* normal
* half-highlighted (enabled by single press)
* fully highlighted (enabled by double press)

I suppose in half highlighted state ctrl key should return to normal after press any key. _This does not happen._

Ok, so I start history search by pressing ctrl once or twice, then press "r", to send ^R (this starts "reverse search" as expected) and then press ctrl again to start typing letters, but tapping ctrl cancels "reverse search" mode!

**Comment by R-033** [comment]
Fixed in upcoming 1.4

**Comment by Self-Perfection** [comment]
Indeed works as expected now, thank you.
